### ISSUE TITLE
Decimal degrees not extracted from text

### ISSUE THREAD

**Issue by erniechapman** [OpenSextant/Xponents#49] opened 2020-04-14 19:19 UTC
**Describe the bug**
Unsure if this is a feature request or a bug report, but we'll start things here.  I expected decimal degrees within a brick of text to be detected much like UTM, MGRS, etc.  Instead the service returned zero results.  

I was just examining the the core configuration for geocoord patterns and I'm not 100% sure if my test case even matches the patterns.  We see this pattern in text frequently without the degrees symbol and it would be great if the service supported them:

`42.312,102.121
42.312, 102.121`

**To Reproduce**
I'm running the service using the latest 3.3 docker image on an EC2 instance running amazon linux 2.   I'm exercising the endpoint utilizing curl like the following example:

`curl -XPOST http://localhost:8888/xlayer/rest/process --data '{"text":"I flew to 42.312,102.121"}' | jq .`

and see the following response:

`{
  "response": {
    "status": "ok",
    "numfound": 0
  },
  "annotations": []
}`

**Expected behavior**
I would have expected the extractor to identify 42.312,102.121 as a location in decimal degrees and perform the same reverse geocode that occurs when utilizing the MGRS or DMS coords.  

Thanks so much!!

**Comment by mubaldino** [comment] 2020-04-14 19:45
Hi Ernie, 

It is between bug and feature.   First, while you have valid coordinates of this form `DD.dd, DDD.dd`, the detection of them in real data (full documents, spreadsheets, social media, etc) in general is so noisy that it is not that worthwhile to consider.  There is a lot of scientific of financial data we've encountered in all sorts of use cases that look like pairs of floating point numbers,... and are potentially decimal degrees, however there's no easy confirmation that they actually are geographic in nature.

So the solution -- as an end user -- here is to grab a copy of [geocoord_patterns.cfg](https://github.com/OpenSextant/Xponents/blob/master/Core/src/main/resources/geocoord_patterns.cfg) and adapt a `DD` pattern to account for your use case.  Give it a new enumeration, like `DD   06`.   Next insert that into the front of your classpath, so it overrides the default.

On towards a docker deployment you can see how this might be fielded, you could rebuild the docker image using the existing baseline and overlay your version into `./Xponents*/etc/` which is in the `CLASSPATH` for the REST server script.

Before that, though you would need to experiment with the Xponents SDK from source, or build your own app pulling in the latest artifacts from Maven.

If you're not hot on Java, it might take me a few days to get tested solution for that `.cfg` tweak.   My gut feeling here is that your request needs only a `RULE` pattern defined and no recompilation of Java nonsense is necessary.  I'll spend 10 minutes later today or tomorrow and let you know.

**Comment by mubaldino** [comment] 2020-04-14 20:08
Also, please account for format or style of floating point values -- how do you distinguish in your data these pairs? is it simply comma separated pairs?  `LAT,LON   LAT,LON `:
- `43.21, -45.54  33.22  44.11`  -- a comma-separated pair followed by two other pairs.
- `43.21, -045.54`  -- zero padding is an indicator that is longitude.

Its good to understand the ambiguities in terms of formatting -- is the format `LAT, LON` or XY style as in `LON, LAT`?  Are Longitudes consistently three-digit?  Will West and South be consistently designated with "-", and North/East optionally with a "+"?

**Comment by mubaldino** [comment] 2020-04-16 12:20
Solution:
1. For now make a copy of `geocoord_patterns.cfg`
2. Add this new `RULE` (and `TEST` cases optionally) to the end of the file along with the `DD` family.

```ini
#RULE   DD      08     \b<hemiLatSign>?<decDegLat>,\s?<hemiLonSign>?<decDegLon>
#TEST   DD      08     text 54.67, -117 text  # FAIL - no decimal longitude
#TEST   DD      08     text 54.33, -117.81 text
#TEST   DD      08     text +54.22, 117.71 text
#TEST   DD      08     text +54.22, 045.71 text
#TEST   DD      08     text +54.22, -045.71 text
#TEST   DD      08     text 54.11,117.61 text
#TEST   DD      08     YX = (54.11, 117.61) text   # Coordinate tuple ()
```

3. This copy of the patterns file should go in the front of your CLASSPATH on the docker container.  In essence, Make a new Docker and add your new file in the `./Xponents/etc` `CLASSPATH` folder that is used by the REST service.

```
FROM mubaldino/opensextant:xponents-3.3

COPY ./ernie/geocoord_patterns.cfg Xponents/etc/
```

Alternatively you could recreate the `etc` folder and mount that with the `docker run`, overriding the defaults.

I tested the RULE above.  But the actual employment of it is up to you if you want a docker solution or just to use `XCoord` main program directly as a Java library.   Examples module demonstrates this in source tree.  In distribution it is like this:
https://opensextant.github.io/Xponents/Examples/

```
# make sure your patterns file is in CLASSPATH, like in ./etc
./script/xponents-demo.sh xcoord
```

I believe the issue is solved here.  But I'll close it out when I hear you have picked a mode of implementing it.   I know there's a few ways to invoke it, but development here is still a bit convoluted.

**Comment by erniechapman** [comment] 2020-04-17 12:12
I really appreciate the thoughtful responses Marc.  Based on your feedback, I'm also thinking about how this might generate some bogus results in some datasets, and I'm almost leaning towards excluding this from the DD family in the end.

I'm going to spend some time today modifying the cfg and including that in a new Docker container.  I'll run some data through and see what things look like.

Again, I appreciate the quick and through responses.  This is a great project, thanks for for sharing it!
Ernie

**Comment by mubaldino** [comment] 2021-12-16 01:26
Closing out issue, as this seemed more like a "how-to" than a feature or bug fix.   Thanks for the use case and feedback!

**Closed by mubaldino** 2021-12-16 01:26 UTC
